# Generated by Django 3.1.3 on 2023-05-08 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credly',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='credly  badge', max_length=30)),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
    ]
